# Backpack 价格移动做空网格配置示例

grid_system:
  # 基础设置
  exchange: "backpack"                    # 交易所
  symbol: "BTC_USDC_PERP"                # 交易对
  
  # 网格类型
  grid_type: "follow_short"              # follow_short=价格移动做空网格
  
  # 价格移动网格参数（不需要设置upper_price和lower_price）
  follow_grid_count: 200                 # 网格数量（用户指定）
  grid_interval: 100.00                  # 网格间隔
  follow_timeout: 300                    # 脱离超时时间（秒，默认5分钟）
  follow_distance: 1                     # 脱离距离（网格数，默认1格）
  
  # 订单设置
  order_amount: 0.0001                   # 每格订单数量（BTC）
  
  # 可选设置
  max_position: 5.0                      # 最大持仓限制（建议设置）
  enable_notifications: true             # 是否启用通知
  fee_rate: 0.0001                       # 手续费率（默认0.0001=万分之1）
  
  # 订单健康检查
  order_health_check_interval: 600       # 订单健康检查间隔（秒，默认600=10分钟）
  
  # 说明：
  # 1. 价格区间自动计算：
  #    - 假设当前价格为 100100
  #    - 最低价格 = 100100（当前价格）
  #    - 最高价格 = 100100 + (200 * 100) = 120100
  #    - 挂单范围：100200 ~ 120100（200个卖单）
  #
  # 2. 价格向下脱离（盈利方向）：
  #    - 条件：当前价格 < 最低价格 - (1 * 100)
  #    - 持续时间 > 300秒
  #    - 操作：取消所有订单，以新价格为最低价，重新挂200个卖单
  #
  # 3. 价格向上脱离（亏损方向）：
  #    - 不做任何操作，等待价格恢复
  #
  # 4. 适用场景：
  #    - 下跌趋势行情
  #    - 自动跟随价格下跌
  #    - 避免网格被价格甩在后面
