# Backpack 价格移动做多网格配置示例

grid_system:
  # 基础设置
  exchange: "backpack"                    # 交易所
  symbol: "BTC_USDC_PERP"                # 交易对
  
  # 网格类型
  grid_type: "follow_long"               # follow_long=价格移动做多网格
  
  # 价格移动网格参数（不需要设置upper_price和lower_price）
  follow_grid_count: 200                 # 网格数量（用户指定）
  grid_interval: 50.00                  # 网格间隔
  follow_timeout: 300                    # 脱离超时时间（秒，默认5分钟）
  follow_distance: 2                     # 脱离距离（网格数，默认1格）
  
  # 订单设置
  order_amount: 0.0001                   # 每格订单数量（BTC）
  
  # 可选设置
  max_position: 5.0                      # 最大持仓限制（建议设置）
  enable_notifications: true             # 是否启用通知
  fee_rate: 0.0001                       # 手续费率（默认0.0001=万分之1）
  
  # 订单健康检查
  order_health_check_interval: 600       # 订单健康检查间隔（秒，默认600=10分钟）
  
  # 说明：
  # 1. 价格区间自动计算：
  #    - 假设当前价格为 100100
  #    - 最高价格 = 100100（当前价格）
  #    - 最低价格 = 100100 - (200 * 100) = 80100
  #    - 挂单范围：80200 ~ 100000（200个买单）
  #
  # 2. 价格向上脱离（盈利方向）：
  #    - 条件：当前价格 > 最高价格 + (1 * 100)
  #    - 持续时间 > 300秒
  #    - 操作：取消所有订单，以新价格为最高价，重新挂200个买单
  #
  # 3. 价格向下脱离（亏损方向）：
  #    - 不做任何操作，等待价格恢复
  #
  # 4. 适用场景：
  #    - 上涨趋势行情
  #    - 自动跟随价格上涨
  #    - 避免网格被价格甩在后面
